name: Compress PNGs
on:
  push:
    branches:
      - main
    paths:
      - 'src/memos/images/**'

permissions:
  contents: write

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pngquant
        run: sudo apt-get install -y pngquant

      - name: Compress Images
        run: |
          cd src/memos/images
          pngquant --quality 65-80 --skip-if-larger --ext .png --force *.png || true

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add src/memos/images/*.png
          
          if ! git diff --cached --quiet; then
            git commit -m "chore: optimize png images"
            
            git pull --rebase origin main
            
            git push origin main
          else
            echo "No changes to commit"
          fi